#ifndef ITEMS_H
#define ITEMS_H 

#include "FileIO.h"

enum usesEquip {
EQUIP_HAND, EQUIP_CHEST, EQUIP_HEAD, EQUIP_ARM, EQUIP_LEG, EQUIP_FOOT, EQUIP_NECK, 
EQUIP_SYMMETRY, EQUIP_EDGE, STAB, CRUSH, MAGIC_BOOST, MANA_BOOST, STAFF_BOOST, 
SHIELD, BOW, CROSSBOW, DART_GUN, DART_BLOW, GUN, 
LEVER, TOOL_NO_TECH, TOOL_TECH, TOOL_UNIQUE, KEY
};


enum usesConsume {
POTION_HEAL, BANDAGE, OTHER_MEDICAL, FOOD, POTION_MANA, ELEMENT_CLUSTER, POWER_ELEMENT_CLUSTER,
CRYSTAL_MANA, EXPLODE_DISABLE, EXPLODE_DAMAGE, EXPLODE_FLARE, 
};



class itemSet
{

//Tree implementation







};


#endif
